# docker-compose up -d
elastic-sb:
  image: elastic-sb
  net: host
  volumes:
   - ./elasticsearch/config:/usr/share/elasticsearch/data
   - ./elasticsearch/esdata:/usr/share/elasticsearch/esdata

logstash-fwdr-sb:
  image: logstash-fwdr-sb
  net: host
  volumes:
    - ./logstash-forwarder/config:/opt/conf

logstash-sb:
  image: logstash-sb
  net: host
  volumes:
    - ./logstash/config:/config
  expose:
    - "25826"
  command: logstash -f /config/logstash-collectd.conf

kibana-sb:
  image: kibana-sb
  net: host
