# docker-compose up -d
elastic-sb:
  image: elastic-sb
  hostname: "elastic-sb"
  expose: ["9200", "9300"]
  volumes:
   - ./elasticsearch/config:/usr/share/elasticsearch/data
   - ./elasticsearch/esdata:/usr/share/elasticsearch/esdata
  container_name: "elastic-sb"

logstash-sb:
  image: logstash-sb
  hostname: "logstash-sb"
  expose: ["25826"]
  volumes:
    - ./logstash/config:/config
  container_name: "logstash-sb"
  command: logstash -f /config/11-collectd.conf

kibana-sb:
  image: kibana-sb
  hostname: "kibana-sb"
  expose: ["5601"]
  container_name: "kibana-sb"
